#!/usr/bin/env python3
"""Regenerate paper-ready Markdown tables from cluster `merged_summary.json` files.

Usage on the cluster:
    cd /scratch/$USER/longcat-video-tta
    python3 scripts/build_paper_tables.py --regime headline_1000v \
        --output sweep_experiment/reports/paper_tables/$(date +%Y-%m-%d)_headline_1000v.md

If --output is omitted, prints to stdout.

Regimes:
    headline_1000v : the 4 main paper tables (Panda/UCF × std/long).
    panda_std      : just Panda 1000v standard.
    ucf_std        : just UCF 932v standard (incl. retrieval).
    panda_longctx  : just Panda 1000v long-context.
    ucf_long       : just UCF 683v long-horizon.
    all            : same as headline_1000v.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Iterable, Sequence

DIMS = [
    "subject_consistency",
    "background_consistency",
    "aesthetic_quality",
    "motion_smoothness",
    "dynamic_degree",
    "imaging_quality",
    "temporal_flickering",
]
DIM_SHORT = ["Subj", "BG", "Aes", "Motn", "Dyn", "IQ", "Flick"]

# (title, [series_dirs])
REGIMES: dict[str, list[tuple[str, list[str]]]] = {
    "panda_std": [
        ("Panda 1000v Standard (28 frames)", [
            "sweep_experiment/results/panda_1000v_standard",
            "delta_experiment/results/tinylora_panda_1000v_standard",
        ]),
    ],
    "ucf_std": [
        ("UCF 932v Standard (28 frames)", [
            "sweep_experiment/results/ucf101_932v_standard",
            "delta_experiment/results/tinylora_ucf101_932v_standard",
            "sweep_experiment/results/ucf101_932v_retrieval",
        ]),
    ],
    "panda_longctx": [
        ("Panda 1000v Long-Context (76 frames)", [
            "sweep_experiment/results/panda_longctx_1000v",
            "delta_experiment/results/tinylora_longctx_1000v",
        ]),
    ],
    "ucf_long": [
        ("UCF 683v Long-Horizon (76 frames)", [
            "sweep_experiment/results/ucf101_683v_longhorizon",
        ]),
    ],
}
REGIMES["headline_1000v"] = [
    *REGIMES["panda_std"],
    *REGIMES["ucf_std"],
    *REGIMES["panda_longctx"],
    *REGIMES["ucf_long"],
]
REGIMES["all"] = REGIMES["headline_1000v"]


def _fmt(value, kind: str) -> str:
    if value is None:
        return "-"
    if kind == "int":
        try:
            return str(int(value))
        except (TypeError, ValueError):
            return str(value)
    if isinstance(value, str):
        return value
    if not isinstance(value, (int, float)):
        return "-"
    return {
        "psnr": f"{value:.2f}",
        "ssim": f"{value:.4f}",
        "lpips": f"{value:.4f}",
        "fvd": f"{value:.1f}",
        "fid": f"{value:.2f}",
        "vbench": f"{value:.4f}",
    }.get(kind, f"{value:g}")


def _table_header() -> str:
    cols = ["Method", "N", "PSNR", "SSIM", "LPIPS", "FVD", "FID", *DIM_SHORT]
    sep = ["---"] * len(cols)
    return "| " + " | ".join(cols) + " |\n|" + "|".join(sep) + "|"


def _table_row(method: str, summary: dict) -> str:
    n = summary.get("num_videos") or summary.get("fvd_num_videos") or "-"
    vb = summary.get("vbench") or {}
    cells = [
        method,
        _fmt(n, "int"),
        _fmt(summary.get("psnr"), "psnr"),
        _fmt(summary.get("ssim"), "ssim"),
        _fmt(summary.get("lpips"), "lpips"),
        _fmt(summary.get("fvd"), "fvd"),
        _fmt(summary.get("fid"), "fid"),
        *(_fmt(vb.get(d), "vbench") for d in DIMS),
    ]
    return "| " + " | ".join(cells) + " |"


def _iter_method_summaries(series_dir: str) -> Iterable[tuple[str, dict]]:
    sp = Path(series_dir)
    if not sp.exists():
        return
    for method_dir in sorted(p for p in sp.iterdir() if p.is_dir()):
        f = method_dir / "merged_summary.json"
        if not f.exists():
            continue
        try:
            with open(f) as fh:
                yield method_dir.name, json.load(fh)
        except (json.JSONDecodeError, OSError):
            continue


def render_regime(regime: str) -> str:
    if regime not in REGIMES:
        raise SystemExit(f"Unknown regime '{regime}'. Choices: {list(REGIMES)}")
    parts = [
        "# AdaSteer paper tables — auto-generated",
        "",
        f"Generated by `scripts/build_paper_tables.py --regime {regime}`.",
        f"Source: `merged_summary.json` files under cwd.",
        "",
        "VBench dimensions: Subj=`subject_consistency`, BG=`background_consistency`, "
        "Aes=`aesthetic_quality`, Motn=`motion_smoothness`, Dyn=`dynamic_degree`, "
        "IQ=`imaging_quality`, Flick=`temporal_flickering`.",
        "",
    ]
    for title, series_list in REGIMES[regime]:
        parts.append(f"## {title}")
        parts.append("")
        parts.append(_table_header())
        any_row = False
        for series in series_list:
            for method, summary in _iter_method_summaries(series):
                parts.append(_table_row(method, summary))
                any_row = True
        if not any_row:
            parts.append("| (no `merged_summary.json` found in any series) |" + " |" * (7 + len(DIMS)))
        parts.append("")
        parts.append("Sources:")
        for series in series_list:
            parts.append(f"- `{series}/<METHOD>/merged_summary.json`")
        parts.append("")
    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--regime", default="headline_1000v", choices=list(REGIMES))
    parser.add_argument("--output", default=None,
                        help="Write to file instead of stdout. Parent dirs are created.")
    args = parser.parse_args()
    text = render_regime(args.regime)
    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text)
        print(f"Wrote {out}")
    else:
        print(text)


if __name__ == "__main__":
    main()
