#!/usr/bin/env python3
"""Significance / "is it just randomness?" analysis for the budget-grid router.

Answers three precise forms of "is the 12-config (and 13-action) router winning
from randomness, and is the oracle headroom real?":

  (1) Is the router's realized gain > 0 beyond sampling noise?
      -> paired bootstrap 95% CI + sign-flip permutation p-value on the per-video
         paired deltas d_i = realized(router_i) - fixed_i (and vs NO-TTA).

  (2) Does the router beat *random targeting*?  Two nulls:
        - random_pick   : uniform-random valid config per video (13-action also
                          allows the NO-TTA action). "Better than a coin flip?"
        - shuffle_picks : keep the EXACT multiset of the router's own picks (so
                          the config-usage marginal is identical) but permute
                          WHICH video gets which pick. Any gain above this null
                          is genuine per-video adaptivity, not just a good
                          average config choice. This is the sharpest test.
      Plus argmax match-rate vs the 1/k chance floor (binomial).

  (3) Is the oracle headroom real signal or "max over noise"?
      -> parametric noise-floor simulation: assume all configs are truly equal
         per video and differ only by Gaussian measurement noise with sigma
         estimated from the observed across-config spread; simulate the
         resulting max-over-k minus fixed. If the observed oracle headroom is
         within this noise-floor band, the oracle is essentially unroutable
         max-over-noise (consistent with the routability R^2 <= 0 diagnostic).

Router picks are the SAME leakage-free 5-fold OOF ridge picks as
run_router_full_matrix.py (imported primitives), so the numbers line up with the
reported router matrix. Offline: reuses cached per-config metrics + features, no
generation, no GPU.

Usage:
    python3 scripts/router_significance_analysis.py \
      --series-root sweep_experiment/results/panda_ood_budget_1000v_preview \
      --feature-date sweep_experiment/reports/per_video_analysis/2026-07-12 \
      --output-dir sweep_experiment/reports/per_video_analysis/2026-07-31/router_significance \
      --metrics psnr vbench --blocks A+B+C --actions 12 13
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

_REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO))

from scripts.budget_routing_common import load_pilot_bundle  # noqa: E402
from scripts.run_routing_tricks import (  # noqa: E402
    _nanmean,
    _oof_config_predict,
    _realized_from_pick,
)
from scripts.run_router_full_matrix import (  # noqa: E402
    BLOCKS,
    BLOCK_ORDER,
    _load_notta,
    _subset_X,
)


# ---------------------------------------------------------------------------
# statistics helpers
# ---------------------------------------------------------------------------

def paired_bootstrap_ci(
    d: np.ndarray, *, n_boot: int, seed: int, ci: float = 95.0
) -> Tuple[float, float, float]:
    """Percentile bootstrap CI for mean(d) (paired resample of videos)."""
    d = np.asarray(d, dtype=float)
    d = d[np.isfinite(d)]
    if d.size == 0:
        return float("nan"), float("nan"), float("nan")
    rng = np.random.default_rng(seed)
    n = d.size
    means = np.empty(n_boot, dtype=float)
    for b in range(n_boot):
        means[b] = d[rng.integers(0, n, n)].mean()
    lo = float(np.percentile(means, (100 - ci) / 2))
    hi = float(np.percentile(means, 100 - (100 - ci) / 2))
    return float(d.mean()), lo, hi


def sign_flip_p(d: np.ndarray, *, n_perm: int, seed: int) -> float:
    """Two-sided sign-flip permutation p for H0: mean(d) = 0.

    Under H0 (paired deltas symmetric about 0), the sign of each d_i is
    exchangeable; the null distribution of the mean is generated by random
    sign flips. Returns the two-sided p-value.
    """
    d = np.asarray(d, dtype=float)
    d = d[np.isfinite(d)]
    if d.size == 0:
        return float("nan")
    obs = abs(float(d.mean()))
    rng = np.random.default_rng(seed)
    n = d.size
    cnt = 0
    for _ in range(n_perm):
        signs = rng.integers(0, 2, n) * 2 - 1
        if abs(float((d * signs).mean())) >= obs:
            cnt += 1
    return (cnt + 1) / (n_perm + 1)


def _row_finite_choice(row: np.ndarray, rng: np.random.Generator) -> int:
    """Uniformly pick a column index among the finite entries of *row*."""
    fin = np.where(np.isfinite(row))[0]
    if fin.size == 0:
        return -1
    return int(fin[rng.integers(0, fin.size)])


def random_pick_null(
    Y_use: np.ndarray, fixedm: np.ndarray, *, n_draw: int, seed: int
) -> np.ndarray:
    """Null distribution of mean(realized - fixed) for a uniform-random picker.

    Y_use is n x K (K=12 for 12-action, 13 with the NO-TTA column appended).
    Each draw picks, per video, a uniformly random valid (finite) column.
    """
    rng = np.random.default_rng(seed)
    n = Y_use.shape[0]
    gains = np.empty(n_draw, dtype=float)
    for b in range(n_draw):
        realized = np.full(n, np.nan, dtype=float)
        for i in range(n):
            j = _row_finite_choice(Y_use[i], rng)
            if j >= 0:
                realized[i] = Y_use[i, j]
        gains[b] = _nanmean(realized - fixedm)
    return gains


def shuffle_picks_null(
    Y_use: np.ndarray,
    pick: np.ndarray,
    fixedm: np.ndarray,
    *,
    n_draw: int,
    seed: int,
) -> Tuple[np.ndarray, np.ndarray]:
    """Null where the router's own picks are permuted across videos.

    Keeps the exact multiset of picks (identical config-usage marginal) but
    randomizes which video receives which pick. Returns (null_gains, valid_mask)
    where valid_mask marks videos with a real pick used for the matched observed
    gain. Any observed gain above this null is per-video targeting signal.
    """
    valid = pick >= 0
    idx = np.where(valid)[0]
    picks_valid = pick[idx].astype(int)
    rng = np.random.default_rng(seed)
    gains = np.empty(n_draw, dtype=float)
    for b in range(n_draw):
        perm = rng.permutation(picks_valid)
        realized = np.full(len(pick), np.nan, dtype=float)
        for r, i in enumerate(idx):
            j = perm[r]
            if 0 <= j < Y_use.shape[1] and np.isfinite(Y_use[i, j]):
                realized[i] = Y_use[i, j]
        gains[b] = _nanmean(realized[valid] - fixedm[valid])
    return gains, valid


def oracle_noise_floor(
    Ym: np.ndarray, fixed_col: int, *, n_sim: int, seed: int
) -> Tuple[float, float, float, float]:
    """Parametric 'max-over-noise' null for the config-oracle headroom.

    Model: for each video i the K configs have the SAME true value mu_i and
    differ only by i.i.d. Gaussian noise with std sigma_i estimated from the
    observed across-config spread for that video. Simulate K noisy configs,
    take max - (the fixed column's noisy draw), average over videos. This is
    the oracle headroom you'd expect if configs carry no per-video signal.

    Returns (mean, lo95, hi95, mean_sigma). NOTE sigma_i estimated from the same
    values slightly *over*-states real signal (so this null is conservative:
    if the observed headroom is still <= this floor, it is squarely noise).
    """
    rng = np.random.default_rng(seed)
    n, k = Ym.shape
    # per-video mean/std over finite configs
    mu = np.full(n, np.nan)
    sig = np.full(n, np.nan)
    for i in range(n):
        row = Ym[i][np.isfinite(Ym[i])]
        if row.size >= 2:
            mu[i] = row.mean()
            sig[i] = row.std(ddof=1)
    ok = np.isfinite(mu) & np.isfinite(sig)
    mu_ok, sig_ok = mu[ok], sig[ok]
    m = mu_ok.size
    if m == 0:
        return float("nan"), float("nan"), float("nan"), float("nan")
    sims = np.empty(n_sim, dtype=float)
    fc = int(fixed_col)
    for b in range(n_sim):
        noise = rng.standard_normal((m, k)) * sig_ok[:, None]
        vals = mu_ok[:, None] + noise
        head = vals.max(axis=1) - vals[:, fc]
        sims[b] = float(head.mean())
    return (
        float(sims.mean()),
        float(np.percentile(sims, 2.5)),
        float(np.percentile(sims, 97.5)),
        float(np.nanmean(sig_ok)),
    )


def _one_sided_p(null: np.ndarray, observed: float) -> float:
    """P(null gain >= observed): how often random targeting matches/beats it."""
    null = null[np.isfinite(null)]
    if null.size == 0 or not math.isfinite(observed):
        return float("nan")
    return float((np.sum(null >= observed) + 1) / (null.size + 1))


# ---------------------------------------------------------------------------
# per-(metric, block, actions) analysis
# ---------------------------------------------------------------------------

def analyze_one(
    metric: str,
    block: str,
    actions: int,
    bundle: dict,
    args: argparse.Namespace,
) -> dict:
    vids: List[str] = bundle["video_ids"]
    grid_runs: List[str] = bundle["grid_runs"]
    Y_full = np.array(bundle["psnr" if metric == "psnr" else "Y_total"], dtype=float)
    notta_full = _load_notta(args.series_root, vids, metric)

    pool = ~np.all(np.isnan(Y_full), axis=1) & ~np.isnan(notta_full)
    n = int(pool.sum())
    if n < 30:
        raise SystemExit(f"[error] metric={metric}: only {n} videos with config+NOTTA.")

    # fixed = best population-mean config on the paired pool (matches the matrix)
    with np.errstate(invalid="ignore"):
        col_means = np.array([
            np.nanmean(Y_full[pool, j]) if np.any(~np.isnan(Y_full[pool, j])) else -np.inf
            for j in range(Y_full.shape[1])
        ])
    best_idx = int(np.argmax(col_means))
    fixed_run = grid_runs[best_idx]

    Ym = Y_full[pool]
    nottam = notta_full[pool]
    fixedm = Y_full[pool, best_idx]
    vids_pool = [vids[i] for i in range(len(vids)) if pool[i]]
    config_oracle = np.nanmax(Ym, axis=1)
    aug_oracle = np.maximum(config_oracle, nottam)

    X, nfeat = _subset_X(args.feature_date, vids_pool, bundle, BLOCKS[block])

    k = Ym.shape[1]
    if actions == 13:
        Y_use = np.column_stack([Ym, nottam])
        oracle = aug_oracle
        oracle_name = "augmented (incl. NO-TTA)"
    else:
        Y_use = Ym
        oracle = config_oracle
        oracle_name = "config (best of 12)"

    pick, _, lam = _oof_config_predict(X, Y_use, args.n_folds, args.seed)
    realized = _realized_from_pick(Y_use, pick)

    # ---- (1) realized gain: bootstrap CI + sign-flip p ----
    d_fix = realized - fixedm
    d_ntt = realized - nottam
    mean_fix, lo_fix, hi_fix = paired_bootstrap_ci(d_fix, n_boot=args.n_boot, seed=args.seed)
    mean_ntt, lo_ntt, hi_ntt = paired_bootstrap_ci(d_ntt, n_boot=args.n_boot, seed=args.seed + 1)
    p_fix = sign_flip_p(d_fix, n_perm=args.n_perm, seed=args.seed + 2)
    p_ntt = sign_flip_p(d_ntt, n_perm=args.n_perm, seed=args.seed + 3)

    # ---- (2) randomness nulls ----
    rnd = random_pick_null(Y_use, fixedm, n_draw=args.n_perm, seed=args.seed + 4)
    shuf, valid = shuffle_picks_null(Y_use, pick, fixedm, n_draw=args.n_perm, seed=args.seed + 5)
    obs_gain_valid = _nanmean(realized[valid] - fixedm[valid])
    p_random = _one_sided_p(rnd, mean_fix)
    p_shuffle = _one_sided_p(shuf, obs_gain_valid)

    # match rate vs 1/k chance
    argmax_true = np.array([
        int(np.nanargmax(Ym[i])) if not np.all(np.isnan(Ym[i])) else -1
        for i in range(n)
    ])
    mt_mask = argmax_true >= 0
    match = float(np.mean((pick[mt_mask] == argmax_true[mt_mask]))) if mt_mask.any() else float("nan")
    chance = 1.0 / k

    # ---- (3) oracle headroom + noise floor ----
    head_cfg = config_oracle - fixedm
    mean_head, lo_head, hi_head = paired_bootstrap_ci(head_cfg, n_boot=args.n_boot, seed=args.seed + 6)
    nf_mean, nf_lo, nf_hi, nf_sigma = oracle_noise_floor(
        Ym, best_idx, n_sim=args.n_sim, seed=args.seed + 7
    )

    apply_rate = float(np.mean(pick != k)) if actions == 13 else 1.0

    return {
        "metric": metric,
        "block": block,
        "actions": actions,
        "n": n,
        "n_feat": int(nfeat),
        "fixed_run": fixed_run,
        "lam": lam,
        "apply_rate": apply_rate,
        # (1)
        "policy_mean": _nanmean(realized),
        "fixed_mean": _nanmean(fixedm),
        "notta_mean": _nanmean(nottam),
        "d_vs_fixed": mean_fix, "d_vs_fixed_lo": lo_fix, "d_vs_fixed_hi": hi_fix,
        "p_signflip_vs_fixed": p_fix,
        "d_vs_notta": mean_ntt, "d_vs_notta_lo": lo_ntt, "d_vs_notta_hi": hi_ntt,
        "p_signflip_vs_notta": p_ntt,
        # (2)
        "random_null_mean": float(np.mean(rnd)),
        "random_null_hi95": float(np.percentile(rnd, 97.5)),
        "p_vs_random": p_random,
        "shuffle_null_mean": float(np.mean(shuf)),
        "shuffle_null_hi95": float(np.percentile(shuf, 97.5)),
        "obs_gain_on_valid": obs_gain_valid,
        "p_vs_shuffle": p_shuffle,
        "match_rate": match,
        "match_chance": chance,
        # (3)
        "oracle_name": oracle_name,
        "config_oracle_headroom": mean_head,
        "config_oracle_headroom_lo": lo_head,
        "config_oracle_headroom_hi": hi_head,
        "noise_floor_mean": nf_mean,
        "noise_floor_lo": nf_lo,
        "noise_floor_hi": nf_hi,
        "noise_sigma_mean": nf_sigma,
        "captured_of_config_oracle": (
            mean_fix / mean_head if abs(mean_head) > 1e-9 else float("nan")
        ),
    }


def _verdict(r: dict) -> str:
    beats_fixed = (r["d_vs_fixed_lo"] > 0) and (r["p_signflip_vs_fixed"] < 0.05)
    beats_random = math.isfinite(r["p_vs_random"]) and r["p_vs_random"] < 0.05
    beats_shuffle = math.isfinite(r["p_vs_shuffle"]) and r["p_vs_shuffle"] < 0.05
    if beats_fixed and beats_shuffle:
        return "REAL per-video signal (beats fixed AND own-shuffle null)"
    if beats_fixed and not beats_shuffle:
        return "gain is a marginal-config effect, NOT per-video targeting (fails shuffle null)"
    if not beats_fixed and beats_random:
        return "beats a coin flip but NOT the best fixed config (CI incl. 0)"
    return "indistinguishable from randomness (CI incl. 0; fails nulls)"


def _oracle_verdict(r: dict) -> str:
    obs = r["config_oracle_headroom"]
    nf = r["noise_floor_mean"]
    nf_hi = r["noise_floor_hi"]
    if not (math.isfinite(obs) and math.isfinite(nf)):
        return "n/a"
    if obs <= nf_hi:
        return "consistent with MAX-OVER-NOISE (observed within noise-floor band)"
    frac = (obs - nf) / obs if abs(obs) > 1e-9 else float("nan")
    return f"exceeds noise floor by {frac:.0%} of headroom (some real config structure)"


def _f(x, nd=4):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "—"
    return f"{x:.{nd}f}"


def _fd(x, nd=4):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "—"
    return f"{x:+.{nd}f}"


def _fp(x):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "—"
    return f"{x:.3f}"


def main() -> int:
    ap = argparse.ArgumentParser(description="Router significance / randomness analysis")
    ap.add_argument(
        "--series-root", type=Path,
        default=_REPO / "sweep_experiment/results/panda_ood_budget_1000v_preview",
    )
    ap.add_argument(
        "--feature-date", type=Path,
        default=_REPO / "sweep_experiment/reports/per_video_analysis/2026-07-12",
    )
    ap.add_argument("--output-dir", type=Path, required=True)
    ap.add_argument("--metrics", nargs="+", default=["psnr", "vbench"],
                    choices=("psnr", "vbench"))
    ap.add_argument("--blocks", nargs="+", default=["A+B+C"], choices=BLOCK_ORDER)
    ap.add_argument("--actions", nargs="+", type=int, default=[12, 13], choices=(12, 13))
    ap.add_argument("--n-folds", type=int, default=5)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--n-boot", type=int, default=10000, help="bootstrap resamples")
    ap.add_argument("--n-perm", type=int, default=10000, help="permutation / null draws")
    ap.add_argument("--n-sim", type=int, default=5000, help="oracle noise-floor sims")
    args = ap.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    rows: List[dict] = []
    for metric in args.metrics:
        bundle = load_pilot_bundle(
            args.series_root, args.feature_date, require_vbench=(metric == "vbench")
        )
        for block in args.blocks:
            for actions in args.actions:
                r = analyze_one(metric, block, actions, bundle, args)
                r["router_verdict"] = _verdict(r)
                r["oracle_verdict"] = _oracle_verdict(r)
                rows.append(r)
                print(
                    f"[{metric} {block} act={actions}] "
                    f"Δfix={_fd(r['d_vs_fixed'])} CI[{_fd(r['d_vs_fixed_lo'])},"
                    f"{_fd(r['d_vs_fixed_hi'])}] p_flip={_fp(r['p_signflip_vs_fixed'])} "
                    f"p_shuf={_fp(r['p_vs_shuffle'])} -> {r['router_verdict']}",
                    file=sys.stderr,
                )

    unit = {"psnr": "dB", "vbench": "raw-total"}
    lines = [
        "# Router significance / \"is it just randomness?\" analysis",
        "",
        f"**Series:** `{args.series_root.name}`  ·  **Features:** `{args.feature_date.name}`  ·  "
        f"5-fold OOF ridge (seed {args.seed}); bootstrap={args.n_boot}, "
        f"perm/null={args.n_perm}, noise-sim={args.n_sim}.",
        "",
        "Same OOF picks as the router matrix. `fixed` = best population-mean config on "
        "the paired pool. All Δ are mean(policy − baseline). Sign-flip p tests "
        "mean Δ = 0; `p_random` / `p_shuffle` = P(null ≥ observed).",
        "",
        "## (1) Router realized gain — bootstrap 95% CI + sign-flip test",
        "",
        "| Metric | Block | Act | N | Δ vs fixed [95% CI] | p_flip | Δ vs NOTTA [95% CI] | p_flip |",
        "|---|---|---:|---:|---|---:|---|---:|",
    ]
    for r in rows:
        u = unit[r["metric"]]
        lines.append(
            f"| {r['metric']} | {r['block']} | {r['actions']} | {r['n']} | "
            f"{_fd(r['d_vs_fixed'])} [{_fd(r['d_vs_fixed_lo'])}, {_fd(r['d_vs_fixed_hi'])}] {u} | "
            f"{_fp(r['p_signflip_vs_fixed'])} | "
            f"{_fd(r['d_vs_notta'])} [{_fd(r['d_vs_notta_lo'])}, {_fd(r['d_vs_notta_hi'])}] {u} | "
            f"{_fp(r['p_signflip_vs_notta'])} |"
        )
    lines += [
        "",
        "## (2) Randomness nulls — does the router beat random targeting?",
        "",
        "`random_pick` = uniform random valid config/video. `shuffle_picks` = the "
        "router's OWN picks permuted across videos (same config-usage marginal, random "
        "targeting) — gain above this = genuine per-video adaptivity. `match%` vs "
        "`chance` = argmax hit-rate vs 1/k.",
        "",
        "| Metric | Block | Act | Δ vs fixed | random null (mean / hi95) | p_rand | shuffle null (mean / hi95) | p_shuf | match% / chance |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        lines.append(
            f"| {r['metric']} | {r['block']} | {r['actions']} | {_fd(r['d_vs_fixed'])} | "
            f"{_fd(r['random_null_mean'])} / {_fd(r['random_null_hi95'])} | {_fp(r['p_vs_random'])} | "
            f"{_fd(r['shuffle_null_mean'])} / {_fd(r['shuffle_null_hi95'])} | {_fp(r['p_vs_shuffle'])} | "
            f"{_fp(r['match_rate'])} / {_fp(r['match_chance'])} |"
        )
    lines += [
        "",
        "## (3) Oracle headroom vs the max-over-noise floor",
        "",
        "`config-oracle headroom` = mean(best-of-12 − fixed) with bootstrap CI. "
        "`noise floor` = simulated headroom if configs were equal per video + Gaussian "
        "noise (σ from the observed across-config spread). Observed ≈ floor ⇒ the "
        "oracle is essentially max-over-noise (unroutable).",
        "",
        "| Metric | Block | Act | oracle headroom [95% CI] | noise floor [95% CI] | σ | captured by router |",
        "|---|---|---:|---|---|---:|---:|",
    ]
    for r in rows:
        u = unit[r["metric"]]
        lines.append(
            f"| {r['metric']} | {r['block']} | {r['actions']} | "
            f"{_fd(r['config_oracle_headroom'])} [{_fd(r['config_oracle_headroom_lo'])}, "
            f"{_fd(r['config_oracle_headroom_hi'])}] {u} | "
            f"{_fd(r['noise_floor_mean'])} [{_fd(r['noise_floor_lo'])}, {_fd(r['noise_floor_hi'])}] {u} | "
            f"{_f(r['noise_sigma_mean'])} | {_fp(r['captured_of_config_oracle'])} |"
        )
    lines += ["", "## Verdicts", ""]
    for r in rows:
        lines.append(
            f"- **{r['metric']} / {r['block']} / {r['actions']}-action:** "
            f"router → _{r['router_verdict']}_; oracle → _{r['oracle_verdict']}_."
        )
    lines.append("")

    (args.output_dir / "router_significance.json").write_text(
        json.dumps(rows, indent=2, default=str), encoding="utf-8"
    )
    report = args.output_dir / "router_significance_summary.md"
    report.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
